### ISSUE TITLE
filter compile not working with Jade filters via Grunt

### ISSUE THREAD

**Issue by Grawl** [gruntjs/grunt-contrib-pug#103]
I don't know where I can get help with this so I will write this issue into all related repositories: this, [`visionmedia/jade#1503`](https://github.com/visionmedia/jade/issues/1503) and [`btwael/mammouth#36`](https://github.com/btwael/mammouth/issues/36).

I am trying to add Mammouth filter to [`grunt-contrib-jade`](https://github.com/gruntjs/grunt-contrib-jade).

`filters.js`

``` js
var jadefilters=module.exports={};
jadefilters.mammouth=function(str){
    return require('mammouth').compile(str);
};
```

`gruntfile.coffee`

``` coffee
        jade:
            compile:
                options:
                    data:(dest,src) ->
                        return require('./locals.json')
                    filters: require('./filters.js')
                files:[
                    expand:true
                    cwd:'<%=locals.path.src%>/templates/'
                    src:'*.jade'
                    dest:'<%=locals.path.dev%>'
                    ext:'.php'
                ]
```

`index.jade`

``` jade
doctype html
html
    body
        :mammouth
            list = [1, 2, 3, 4, 5]
```

And I get this:

```
Running "jade:compile" (jade) task
[ { type: 'embed', content: 'list = [1, 2, 3, 4, 5]' } ]
File test/index.php created.
```

So I have Mammouth code instead of compiled PHP.

`index.php`

``` html
<!DOCTYPE html><html><body>list = [1, 2, 3, 4, 5]</body></html>
```

But I want to get this:

`index.php`

``` php
<!DOCTYPE html><html><body><?$list = array(1, 2, 3, 4, 5);?></body></html>
```

`mammouth` is installed globally and in a project with `sudo npm install --save`.

**Comment by Grawl** [comment]
I have separated to modules `gruntfile`, based on [`generator-yeogurt`](https://github.com/larsonjj/generator-yeogurt) output and customized by me.

`grunt/config/compile/jade.js`:

```js
// Configuration for jade task(s)
// Compile jade templates into HTML
'use strict';
var taskConfig=function(grunt){
	grunt.config.set('jade', {
		server: {
			options: {
				pretty: true,
				client: false,
				data: {
					debug: true
				},
				filters: {
					sass: function(block){
						return require('node-sass').render(block);
					}
				}
			},
			expand: true,
			cwd: '<%= yeogurt.client %>/templates/',
			dest: '<%= yeogurt.tmp %>/',
			src: [
				'*.jade',
				'!_*.jade'
			],
			ext: '.html'
		},
		dist: {
			// the same with different output and disabled `debug`
		},
	});
};
module.exports=taskConfig;
```

Error:

```
Running "jade:server" (jade) task
>> TypeError: client/templates/index.jade:31
>>     29| 		.columns
>>     30| 			style
>>   > 31| 			:sass
>>     32| 					#collider-depth
>>     33| 						position: absolute
>>     34| 						top: 0
>> 
>> Cannot convert null to object
Warning: Jade failed to compile "client/templates/index.jade". Use --force to continue.

Aborted due to warnings.
```

*Notes*:

- `node-sass` is installed into this project and saved into `project.json` with `--save-dev`
- `grunt-contrib-jade 0.14.1`

I created a test repo to show you that this feature is actually not working even in simplest build: https://github.com/Grawl/jade-filters

Only `:coffee` and `:styl` is working. I think they are hardcoded in `jade` or `grunt-contrib-jade`.

**Comment by shinnn** [comment]
`sass.render` is an asynchronous function. https://github.com/sass/node-sass#render-callback--v300

**Comment by Grawl** [comment]
@shinnn I cannot understand how to use it 😐

**Comment by shinnn** [comment]
@Grawl Use `sass.renderSync` instead.

https://github.com/sass/node-sass/blob/a0bd310482edc071259b16c656456a64a5c28dd0/lib/index.js#L326-L367

**Comment by Grawl** [comment]
@shinnn I already tried this and got an error:

```
>> {
>>   "status": 3,
>>   "message": "File context created without an input path"
>> }
```

I look at `renderSync` code and don't see any input, only parameters object.

**Comment by shinnn** [comment]
@Grawl It's not related to grunt-contrib-jade.

**Comment by Grawl** [comment]
@shinnn agree. But can you help me with this? Maybe Gitter.

**Comment by shinnn** [comment]
@Grawl It's better to ask the authors of [jade](https://github.com/jadejs/jade) or [node-sass](https://github.com/sass/node-sass) about it, instead of us.
