### ISSUE TITLE
jade  compile  exist file

### ISSUE THREAD

**Issue by tamamadesu** [gruntjs/grunt-contrib-pug#106]
now i have some jade files, config like this：

```
files:[{
            cwd: "jade",
            src: "*.jade",
            dest: "public/",
            expand: true,
            ext: ".html"
          }]
```

but, when |  change one file , the all jade files compiled, I dont want this ,because it made my iterm very slow , how |  config it ? thx!

**Comment by juanbrujo** [comment]
@tamamadesu use [grunt-newer](https://github.com/tschaub/grunt-newer) to solve that
