### ISSUE TITLE
Grunt Plugin Renaming jade -> pug

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt-contrib-pug#156]
@shinnn @XhmikosR @shama do we need to rename this plugin or something to work with https://github.com/pugjs/jade/issues/2184 ?

**Comment by shinnn** [comment]
Um, as the *Jade* maintainer said, really unfortunate...

Yes, as @vladikoff said, we need to rename this plugin to `grunt-contrib-pug` in the future, but I think it's better to wait until current Jade repo (https://github.com/pugjs/jade) is renamed.

**Comment by vladikoff** [comment]
cool thanks!

**Comment by XhmikosR** [comment]
Yeah, I totally agree with @shinnn :+1:

**Comment by XhmikosR** [comment]
@vladikoff @shama: so how do we proceed with this? Jade has already been renamed to Pug.

**Comment by shama** [comment]
I've got a new repo started for the rename: https://github.com/gruntjs/grunt-contrib-pug
Once that one is ready, we can publish a new version deprecating this repo and let people know it has been renamed.

**Comment by XhmikosR** [comment]
Why don't we just rename everything and the repo? Something similar to what Jade did.

And for npm there must be a way to show a message.

**Comment by shama** [comment]
@XhmikosR Sure we could just rename this repo instead. I think we'll still have to deprecate `grunt-contrib-jade` though as afaik, npm doesnt have a way to rename a package. Just deprecate the old with a message that says it's renamed.

**Comment by XhmikosR** [comment]
It should be possible to show a message for npm but I haven't done it myself.

So for the repo, create a branch here, rename everything, make a PR to verify, merge the PR, then rename the repo. And finally take care of npm.

**Comment by shama** [comment]
Cool. Thanks @XhmikosR! I think it's ok to just push directly to `master`. I've started on the rename here: b731379a3a706e4de2c8bd5d1e45ade731bcef97

**Comment by XhmikosR** [comment]
OK, so I see 72 hits in 8 files without CHANGELOG, which we shouldn't change.

**Comment by XhmikosR** [comment]
@shama: I verified everything is OK now in master.

SO only the npm package is left.

**Comment by shama** [comment]
@XhmikosR Rad thank you! Should we publish as `grunt-contrib-pug@1.0.0`?

@shinnn Thanks for adding us to that package!

**Comment by willsteinmetz** [comment]
So when is the new version being pushed out to NPM? It's currently still the old 0.0.0 version that doesn't seem to work correctly.

**Comment by shama** [comment]
@willsteinmetz Sorry my mistake. It looks like I forgot to publish. Thanks for the ping.

**Comment by willsteinmetz** [comment]
@shama No problem. Thanks for updating it! :D
