### ISSUE TITLE
Unpublished 1.0.0 release

### ISSUE THREAD

**Issue by fcsonline** [gruntjs/grunt-contrib-pug#163]
If you check this repository source code you can see that the latest release is the `1.0.0` version. But if you check `grunt-contrib-pug` out in http://www.npmjs.com or you install it with `npm install` you get `0.0.0`.

Could you publish the latest release, please?

Thanks,

**Comment by shinnn** [comment]
https://github.com/gruntjs/grunt-contrib-pug/issues/161#issuecomment-210981690

**Comment by fcsonline** [comment]
Cool! Sorry for the noise... 😬 

If I can help to migrate to the new name, I'm open to do it.
