### ISSUE TITLE
Add option to preset keyword directories

### ISSUE THREAD

**Issue by geoffdavis92** [gruntjs/grunt-contrib-pug#164]
In Jekyll, all files that you want to `{% include %}` are in the `_includes` directory, the layouts in the `_layouts` directory, data in the `_data` directory, etc.

It would be great if Pug could allow users to set an object to map certain keywords such as `include`, `extends`, and `+` (mixins) to set directories. This would keep projects consistent with minimal configuration on a `Gruntfile.js`, and it would keep files terse and nest-friendly, allowing `include ../layouts/includes/filename` to simply be `include filename`.

**Comment by shinnn** [comment]
Open a feature request in https://github.com/pugjs/pug/issues instead.
