### ISSUE TITLE
Anyone else having issues with the filters?

### ISSUE THREAD

**Issue by zmanring** [gruntjs/grunt-contrib-pug#168]
I have a filter under the options object but when I build it gives me an error.

```
Options: namespace="JST", separator="\n\n", amd=false, filters={}
Reading index.pug...OK
>> TypeError: Cannot read property 'filters' of undefined
```

**Comment by shinnn** [comment]
👉 https://stackoverflow.com/ or https://github.com/pugjs/pug/issues

**Comment by zmanring** [comment]
Yeah I got the filters working in `Pug` but not through through the grunt system.

**Comment by shinnn** [comment]
Are you using the same version? Currently this plugin depends on this version: https://github.com/gruntjs/grunt-contrib-pug/blob/563653da682115af43767aa8d1d90343daab9d70/package.json#L20

**Comment by zmanring** [comment]
I was on alpha7 and I reverted, same issue

**Comment by ajwild** [comment]
For anyone else who may run into this issue, I fixed it by adding an empty data object to the options.  If you look at [tasks/pug.js#L69](https://github.com/gruntjs/grunt-contrib-pug/blob/915fc96d344ef5f634c861d5389cd192a91d7302/tasks/pug.js#L69) you can see that `f.orig.data` can end up being undefined if `options.data` is not specified, so the check for filters on [tasks/pug.js#L72](https://github.com/gruntjs/grunt-contrib-pug/blob/915fc96d344ef5f634c861d5389cd192a91d7302/tasks/pug.js#L72) will throw the error.

Maybe the code could be updated to `f.orig.data = data || {};`.

**Comment by franciscop** [comment]
As a side note, if you are `require()`ing the filters then you'll have to manually restart the grunt process instead of relying on `grunt watch`, since the `require()` calls are cached and `grunt watch` does not invalidate this cache.
