### ISSUE TITLE
Can we please have processOutput buildoption

### ISSUE THREAD

**Issue by RachelSatoyama** [gruntjs/grunt-contrib-pug#170]
So basically I believe it would be beneficial to have an opportunity to postprocess generated output just like we can process content via `processContent` option. My use case is pretty simple - I want do add typescript-style export declaration to the generated file. Yet I easily can imagine that there are some other scenarios where this can be handy. 

The change is pretty straightforward and can be something like:
```
  var outputString = output.join(grunt.util.normalizelf(options.separator));

 if (options.processOutput) {
        outputString = options.processOutput(outputString);
}   
```

(plus docs and tests)
So I'll be very glad to proved PR if the very idea is not something the community is against of.

**Comment by shinnn** [comment]
Should be done by another Grunt plugin.
