### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by XhmikosR** [gruntjs/grunt-contrib-pug#174]
@vladikoff: we should release a new version, **v2.0.0**. Perhaps bump to the latest pug regardless of `^` so that we are explicit.

Can you take care of this since I don't have npm rights?

**Comment by XhmikosR** [comment]
bump @vladikoff

**Comment by vladikoff** [comment]
@XhmikosR do we want to release the `^2.0.0-alpha3` though? or should we wait? @XhmikosR added you to npm though

**Comment by XhmikosR** [comment]
@vladikoff: pug seems to be at beta11. Not sure when they'll hit stable... Would be nice if we had more people chime in for this.

**Comment by vladikoff** [comment]
I updated `master` to beta11, so devs can use it from GitHub. Once stable ships then we can push to npm.
