### ISSUE TITLE
Options to configure pretty-printing

### ISSUE THREAD

**Issue by alexreg** [gruntjs/grunt-contrib-pug#178]
Could we get options to configure pretty-printing? Such as indentation size, or whether to use tabs for indentation.

**Comment by shinnn** [comment]
> as indentation size

https://github.com/gruntjs/grunt-contrib-pug#pretty

> whether to use tabs for indentation.

Submit a pull request to pug (*not* grunt-contrib-pug) if needed.

**Comment by alexreg** [comment]
Okay. Surely options will need to be added on grunt-contrib-pug too, even if pug supports it?

**Comment by shinnn** [comment]
No.

**Comment by shinnn** [comment]
> even if pug supports it

Pug team deprecated an option to set indent size and character. If you still want to use it, you can contribute to pug, mature the option and undeprecate it.

**Comment by alexreg** [comment]
Ah. So you're saying that options that aren't recognised by grunt-contrib-pug are forwarded on to pug itself?

**Comment by shinnn** [comment]
Here is not a support forum but an issue tracker. Your question should be asked on StackOverflow instead.

**Comment by alexreg** [comment]
Well, consider it a documentation request, since the documentation is lacking in this regard!
