### ISSUE TITLE
Including Jade Filters

### ISSUE THREAD

**Issue by lmartins** [gruntjs/grunt-contrib-pug#38]
Im not sure this ticket belongs here, sorry if not's the case.
How can I use Jade filters? Im trying to use a markdown filter and i always get:

In order to apply the transform markdown you must install one of "marked","supermarked","markdown-js","markdown"
Warning: Jade failed to compile src/index.jade. Use --force to continue.

**Comment by brunowego** [comment]
Thanks @tkellen, works here! :+1:
