### ISSUE TITLE
Add support for basedir option

### ISSUE THREAD

**Issue by sgtpep** [gruntjs/grunt-contrib-pug#64]
I found mention about this option here: http://stackoverflow.com/questions/11675453/jade-loading-templates-from-different-directories#comment27283495_11677885

It allows to use absolute paths in exclude and include directives (starting with slash).

**Comment by vlatri5264** [comment]
@mathiasschopmans, could you tell me where should I look for these options, please?

**Comment by mathiasschopmans** [comment]
Hi @vlatri5264,
sorry I don't see your problem. 😕 If my previous answer doesn't solve your question, can you please add a link to a repository you're working on.

Maybe the following Gruntfile.js might help you more. Please adjust the paths.
```
module.exports = function(grunt) {

  grunt.initConfig({
    jade: {
      yourTaskName: {
        options: {
          basedir: 'path/to/jade/template-root/',
        },
        files: [{
          expand: true,
          flatten: true,
          cwd: 'path/to/jade/template-root/',
          src: ['*.jade'],
          dest: 'path/to/html/output',
          ext :'.html'
        }]
      }
    }
  });

  grunt.loadNpmTasks('grunt-contrib-jade');
  grunt.registerTask('default', ['jade']);

};
```

**Comment by vlatri5264** [comment]
Thanks, @markdalgleish, your solution works))
