### ISSUE TITLE
Uncaught ReferenceError: jade is not defined 

### ISSUE THREAD

**Issue by janmonschke** [gruntjs/grunt-contrib-pug#76]
Hi,

When using locals in a template, I get `Uncaught ReferenceError: jade is not defined` on the client. I'm using version `0.9.1` but had the same problem today with `0.8.0` and I thought an update might fix it ;)

This is my template:

```
.controls
    label= title
```

This is my config:

```
jade: {
  compile: {
    options: {
      client: true
    },
    files: {
      'public/js/templates.js': [allJadeFiles]
    }
  }
}
```

Am I missing an option?

**Comment by pruett** [comment]
i think i am running into the same issue, can you please elaborate on how/where you are including the jade runtime script?

**Comment by janmonschke** [comment]
@pruett I included the Jade runtime into the client-side JS app: https://github.com/gruntjs/grunt-contrib-jade#client

**Comment by pruett** [comment]
@janmonschke a simple script in the <head>? or was it somehow injected into the grunt compilation process?

**Comment by janmonschke** [comment]
I added it to my client-side code
